from pylab import *

fs2au = 41.3413745758
#da = loadtxt('db_pops_4modes.dat')
da = loadtxt('pyr2.txt')
plot(da[:,0]/fs2au,da[:,1],'--r')#'or',mfc='none')
plot(da[:,0]/fs2au,da[:,2],'--b')#'ob',mfc='none')
da = loadtxt('tests/pyr2_exact.txt')
plot(da[:,0],da[:,1],'-r')
plot(da[:,0],da[:,2],'-b')
#da = loadtxt('throwaway_jumps.dat')
#plot(da[:,0],da[:,1],'-r')
#plot(da[:,0],da[:,2],'-b')
##da = loadtxt('tests/pyr4_lanczos.txt')
#da = loadtxt('tests/pyr4_arnoldi_jumps.txt_traj_0')
##da = loadtxt('tests/pyr4_arnoldi.txt')
#plot(da[:,0]*fs2au,da[:,1],'--k')
#plot(da[:,0]*fs2au,da[:,2],'--c')
#da = loadtxt('tests/chk.pl')
#plot(da[:,0]*fs2au,da[:,1],'--g')
#plot(da[:,0]*fs2au,da[:,2],'--y')
##ylim(0.,1.)
#xlabel('t / au')
#ylabel('pops (t)')
show()
