from pylab import *

fs2au=41.3413745758

# model with q's as lindblad operators
da = loadtxt('pyr4_nonhermitian.txt')
#plot(da[:,0]/fs2au,da[:,1]/(da[:,1]+da[:,2]),'-r',lw=3)
#plot(da[:,0]/fs2au,da[:,2]/(da[:,1]+da[:,2]),'-b',lw=3)
plot(da[:,0]/fs2au,da[:,1],'-r',lw=3)
plot(da[:,0]/fs2au,da[:,2],'-b',lw=3)
plot(da[:,0]/fs2au,da[:,1]+da[:,2],'-k',lw=3)
#da = loadtxt('pyr4_nonhermitian_new.txt')
#plot(da[:,0]/fs2au,da[:,1],'og',mfc='none',markevery=5)
#plot(da[:,0]/fs2au,da[:,2],'oy',mfc='none',markevery=5)
#plot(da[:,0]/fs2au,da[:,1]+da[:,2],'oc',mfc='none',markevery=5)
da = loadtxt('pyr4_nh_qutip.txt')
#plot(da[:,0],da[:,1]/(da[:,1]+da[:,2]),'--g',lw=3)
#plot(da[:,0],da[:,2]/(da[:,1]+da[:,2]),'--y',lw=3)
plot(da[:,0],da[:,1],'--g',lw=3)
plot(da[:,0],da[:,2],'--y',lw=3)
plot(da[:,0],da[:,1]+da[:,2],'--c',lw=3)
da = loadtxt('chk_nh.pl')
#plot(da[:,0],da[:,1]/(da[:,1]+da[:,2]),'--or',markevery=20)
#plot(da[:,0],da[:,2]/(da[:,1]+da[:,2]),'--ob',markevery=20)
plot(da[:,0],da[:,1],'--or',markevery=20)
plot(da[:,0],da[:,2],'--ob',markevery=20)
plot(da[:,0],da[:,1]+da[:,2],'--ok',markevery=20)
ylim(0,1)
show()

# model with a's as lindblad operators
da = loadtxt('stronger/pyr4_nonhermitian_down.txt')
#plot(da[:,0]/fs2au,da[:,1]/(da[:,1]+da[:,2]),'-r',lw=3)
#plot(da[:,0]/fs2au,da[:,2]/(da[:,1]+da[:,2]),'-b',lw=3)
plot(da[:,0]/fs2au,da[:,1],'-r',lw=3)
plot(da[:,0]/fs2au,da[:,2],'-b',lw=3)
plot(da[:,0]/fs2au,da[:,1]+da[:,2],'-k',lw=3)
da = loadtxt('pyr4_nh_qutip_down.txt')
#plot(da[:,0],da[:,1]/(da[:,1]+da[:,2]),'--g',lw=3)
#plot(da[:,0],da[:,2]/(da[:,1]+da[:,2]),'--y',lw=3)
plot(da[:,0],da[:,1],'--g',lw=3)
plot(da[:,0],da[:,2],'--y',lw=3)
plot(da[:,0],da[:,1]+da[:,2],'--c',lw=3)
ylim(0,1)
show()
